run_name: OLMo-small-3
seed: 6198
dry_run: false

# wandb:
#name: olmo-test
# project: olmo-small


model:
  d_model: 768
  n_heads: 12
  n_layers: 3
  mlp_ratio: 4
  weight_tying: false
  alibi: false
  rope: true
  flash_attention: true  # not available on AMD
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: false
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 1024
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 50279
  pad_token_id: 1
  init_device: meta
  init_fn: normal
  init_std: 0.02

compile: null  # causes instability on AMD GPUs

optimizer:
  name: adamw
  learning_rate: 1.0e-3
  weight_decay: 0.0
  eps: 1.0e-12
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

wandb:
  name: olmo-d${model.d_model}-h${model.n_heads}-L${model.n_layers}
  project: c4_scaling_expts
  entity: blake_bordelon

scheduler:
  name: cosine_with_warmup
  t_warmup: 2000
  alpha_f: 0.1

tokenizer:
  identifier: tokenizers/allenai_eleuther-ai-gpt-neox-20b-pii-special.json
  truncate_direction: right


save_folder: /n/netscratch/pehlevan_lab/Lab/bbordelon/olmo/checkpoints/olmo-d${model.d_model}-h${model.n_heads}-L${model.n_layers}
save_overwrite: True
# Sharded checkpoints (best for restarts)
save_interval: 1000
save_num_checkpoints_to_keep: 9
# Unsharded checkpoints (for final storage)
save_interval_unsharded: 10000
save_num_unsharded_checkpoints_to_keep: -1

load_path: null

max_duration: 100000  # 1b tokens
global_train_batch_size: 512 # make smaller so we fit on 4 H100s
device_train_microbatch_size: 32

precision: amp_bf16

fsdp:
  wrapping_strategy: null
  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 20

eval_interval: ${save_interval}
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  # lump all the small datasets together (we still get separate metrics).
  - label: v3-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        v3-small-c4_en-validation:
         - /n/holyscratch01/pehlevan_lab/Users/bbordelon/bbordelon/olmo/data/part-0-00000.npy

  - label: v2-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        v2-small-c4_en-validation:
         - /n/holyscratch01/pehlevan_lab/Users/bbordelon/bbordelon/olmo/data/val.npy
data:
  pad_direction: right
  num_workers: 0
  drop_last: true
  pin_memory: true
  prefetch_factor: 16
  persistent_workers: true
  timeout: 0
  paths:
    - /n/netscratch/pehlevan_lab/Lab/bbordelon/olmo/data/part-000-00000.npy
    - /n/netscratch/pehlevan_lab/Lab/bbordelon/olmo/data/part-001-00000.npy
    - /n/netscratch/pehlevan_lab/Lab/bbordelon/olmo/data/part-002-00000.npy
    - /n/netscratch/pehlevan_lab/Lab/bbordelon/olmo/data/part-003-00000.npy

